Repository shubham7668/hacktober, pull requests merged in 2022-10, with the labels that each got.

#44 Create quickSort.cpp
  Recursion/quickSort.cpp
Labels: hacktoberfest-accepted

#49 Create JosephusProblem.cpp
  Recursion/JosephusProblem.cpp
Labels: hacktoberfest-accepted

#50 Create readme.md
  readme.md
Labels: hacktoberfest-accepted

#54 create tower_of_hanoi
  Recursion/tower_of_hanoi.cpp
Labels: hacktoberfest-accepted

#58 Create Print a pattern without using any loop.java
  Recursion/Print a pattern without using any loop.java
Labels: hacktoberfest-accepted

#47 one file add
  48_Rotate_image.cpp
Labels: hacktoberfest-accepted

#62 Palindrome number in cpp
  palindrome.cpp
Labels: hacktoberfest-accepted

#64 add sudoku solver
  backtracking/Sudoku solver.cpp
Labels: hacktoberfest-accepted

#67 added a simple html page
  index.html
Labels: hacktoberfest-accepted

#83 Added html webpage
  Create a simple Html page/index.html
Labels: hacktoberfest-accepted

#100 TernarySearch
  Searching/TernarySearch.py
  Searching/Ternary_search.cpp
Labels: hacktoberfest-accepted

#101 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted

#106 MaxSubArray.py
  MaxSubArray.py
Labels: hacktoberfest-accepted

#104 Create 3 sum in Python
  3 sum in Python
Labels: hacktoberfest-accepted

#103 Added Code for Linked List Cycle Python
  LinkedListCycle.py
Labels: hacktoberfest-accepted

#102 Adding Portfolio
  Portfolio/IMG/CHO2'S.png
  Portfolio/IMG/NIM--_SET.png
  Portfolio/IMG/PLAY BEAT (952).png
  Portfolio/IMG/ProMart (1).png
  Portfolio/IMG/Screenshot (918).png
  Portfolio/IMG/VANDANA.png
  Portfolio/IMG/bh1.jpg
  Portfolio/IMG/lokeytion.png
  Portfolio/IMG/profile-pic (1).png
  Portfolio/index.html
  Portfolio/style.css
Labels: hacktoberfest-accepted

#111 Added gitignore
  .gitignore
  CodeChef PreviousQuestion/A_Needle_in_the_haystack.exe
  CodeChef PreviousQuestion/A_beautiful_matrix.exe
  CodeChef PreviousQuestion/Add_binary.exe
  CodeChef PreviousQuestion/Again_XOR.exe
  CodeChef PreviousQuestion/Agressive_Cows_SPOJ.exe
  CodeChef PreviousQuestion/CarelessChef.exe
  CodeChef PreviousQuestion/Chef_Loves_1010.exe
  CodeChef PreviousQuestion/Chef_and_Lockout.exe
  CodeChef PreviousQuestion/Chef_and_Profits.exe
  CodeChef PreviousQuestion/Chef_and_Subset_Additions.exe
  CodeChef PreviousQuestion/Chef_and_bird_farm.exe
  CodeChef PreviousQuestion/Chef_and_fixed_deposite.exe
  CodeChef PreviousQuestion/Chef_and_instant_Noodle.exe
  CodeChef PreviousQuestion/Chef_and_riffles.exe
  CodeChef PreviousQuestion/Chef_and_segments.exe
  CodeChef PreviousQuestion/chef_and_shuffle_for_pow_of_2.exe
  CodeChef PreviousQuestion/chef_and_vaccation_transport.exe
  Dynamic Programming/Chochlate_distributions.exe
  Dynamic Programming/Fibbonacci_using_recursion_Lect1.exe
  Dynamic Programming/FindComments.exe
  Dynamic Programming/NumberOfSubsets.cpp
  Dynamic Programming/Subsequences.exe
  Dynamic Programming/Unbounded_Knapsack.cpp
  Dynamic Programming/binary_search_with_condition_on_not_find.exe
  Dynamic Programming/frogJump2.exe
  Longest_SubString_Without_Repeating_Characters/index.html
  Longest_SubString_Without_Repeating_Characters/style.css
  Matrix/Passing2DArraysAsArguements.exe
  Matrix/WaysToCreateMultiDimensionArray.exe
  Matrix/mat.cpp
  Portfolio/index.html
  Portfolio/style.css
  Recursion/Binary_Search.exe
  Recursion/Print_Increasing.exe
  Recursion/fibonnacciNumber.exe
  Recursion/try.exe
  Recursion/xtothepowern.exe
  Searching/RepeatingElementsEfficientSol.exe
  Searching/Ternary_search.cpp
  ZCOSCH.cpp
  course.txt
  jewels/Jewels.c
  jewels/Question.txt
  majority/Question.txt
  majority/majority.c
Labels: hacktoberfest-accepted

#114 Code for Set Matrix Zeroes in python added
  Median_of_Two_Sorted_Arrays.py
Labels: hacktoberfest-accepted

#112 Create Frog 1 - At coder DP set
  Dynamic Programming/Frog 1 - At coder DP set
Labels: hacktoberfest-accepted

#117 Portfolio Website using HTML
  portfolio.html
Labels: hacktoberfest-accepted

#115 Create TwoSum.py
  TwoSum.py
Labels: hacktoberfest-accepted

#71 Binary search recursion in java
  Recursion/binarysearch.java
Labels: hacktoberfest-accepted

#119 Max Sub Array
  Max_SubArray.py
Labels: hacktoberfest-accepted

#121 Create Implement Trie (Prefix Tree) in python
  Implement Trie (Prefix Tree) in python issue
Labels: hacktoberfest-accepted

#113 Info related to Hashing.
  Whole Info about Hashing/183aryan.md
Labels: hacktoberfest-accepted

#123 Maximum sub array code in Javascript
  maxsubarrayjs.js
Labels: hacktoberfest-accepted

#52 HACTOBERFEST
  Java Programs/Basics/Type_check.java
  Java Programs/Basics/calculator.java
  Java Programs/Basics/condition.java
  Java Programs/Basics/condition_and_loops.java
  Java Programs/Basics/fibonnaci.java
  Java Programs/Basics/input.java
  Java Programs/Basics/largest_num.java
  Java Programs/Basics/mynewfile.java
  Java Programs/Basics/nested_switch.java
  Java Programs/Basics/newprog.java
  Java Programs/Basics/occurences.java
  Java Programs/Basics/primitives.java
  Java Programs/Basics/reverse.java
  Java Programs/Basics/sum.java
  Java Programs/Basics/switch_cond.java
  Java Programs/Basics/temprature_conversion.java
  Java Programs/Basics/typecasting.java
  Java Programs/funtion/At_time_init.java
  Java Programs/funtion/Prime.java
  Java Programs/funtion/StrReturn.java
  Java Programs/funtion/String_pass.java
  Java Programs/funtion/VarArgs.java
  Java Programs/funtion/armstrong.java
  Java Programs/funtion/change_value.java
  Java Programs/funtion/method.java
  Java Programs/funtion/overloading.java
  Java Programs/funtion/ref_var.java
  Java Programs/funtion/scope.java
  Java Programs/funtion/shadowing.java
  Java Programs/funtion/swap_funtion.java
  Searching/Find first and last positions of an element in a sorted array.java
Labels: hacktoberfest-accepted

#126 Added Merge Sort in Python
  mergeSortinPython.py
Labels: hacktoberfest-accepted

#118 Valid Parenthesis Code
  valid parenthesis.py
Labels: in-review

#138 Code for Longest Substring without Repeating Characters in python added
  Longest_Substring_without_Repeating_Characters.py
Labels: hacktoberfest-accepted

#139 Website.html patch
  website.html/index.html
  website.html/second.html
Labels: hacktoberfest-accepted

#132 CountDown App (JS,HTML.CSS)
  CountDown App/Images/bg1.jpg
  CountDown App/index.html
  CountDown App/script.js
  CountDown App/style.css
Labels: hacktoberfest-accepted

#130 This file contain solution to MCM DP Q in JAVA.
  matrixChainMultiplication/183aryan.md
Labels: hacktoberfest-accepted

#133 Gallery app
  Gallery_App/Images/Armin.jpg
  Gallery_App/Images/Eren.jpg
  Gallery_App/Images/Erwin.jpg
  Gallery_App/Images/Levi.jpg
  Gallery_App/Images/Mikasa.jpg
  Gallery_App/Images/button.png
  Gallery_App/index.html
  Gallery_App/script.js
  Gallery_App/style.css
Labels: hacktoberfest-accepted

#140 Basic Portfolio using HTML
  Basic Portfolio using HTML/Images/dummy-profile-pic.jpg
  Basic Portfolio using HTML/css/styles.css
  Basic Portfolio using HTML/hobbies.html
  Basic Portfolio using HTML/index.html
  Basic Portfolio using HTML/projects.html
Labels: hacktoberfest-accepted

#141 webDev
  webDev/index.html
Labels: in-review

#156 Updated readme.md
  readme.md
Labels: hacktoberfest-accepted

#154 timer
  index.html
  index.js
  style.css
Labels: hacktoberfest-accepted

#155 Register page in html css
  Create a simple Html page/Register.html
Labels: hacktoberfest-accepted

#158 A Car animation coded with the Project preview added on :)
  car_animation/background.png
  car_animation/car_body.png
  car_animation/car_wheel_left.png
  car_animation/car_wheel_right.png
  car_animation/index.html
  car_animation/project preview.png
  car_animation/script.js
  car_animation/sound.mp3
  car_animation/style.css
  car_animation/track.png
  car_animation/trees.png
Labels: hacktoberfest-accepted

#159 Login Page
  login/index.html
  login/style.css
Labels: hacktoberfest-accepted

#162 Added Boston Hose Prediction Model
  Boston House Prediction/Boston.csv
  Boston House Prediction/HousePricePrediction.ipynb
Labels: hacktoberfest-accepted

#163 pheonix page
  webDev/webd2/web3/pheonix.html
Labels: hacktoberfest-accepted

#175 Portfolio website Landing Page (Open Source Initiative)
  PortFolio Landing Page/assests/WhatsApp Im.jpeg
  PortFolio Landing Page/assests/WhatsApp Image 2021-05-03 at 8.12.35 AM.jpeg
  PortFolio Landing Page/assests/style.css
  PortFolio Landing Page/index.html
Labels: hacktoberfest-accepted

#170 Discord timestamp generator
  DiscordTimestampMaker/generator.js
  DiscordTimestampMaker/index.html
  DiscordTimestampMaker/style.css
Labels: hacktoberfest-accepted

#169 Example of null coalescing in NodeJS
  NullCoalescingJS/example.js
Labels: hacktoberfest-accepted

#173 Created a Wifi AutoConnector using Python
  wifiAutoConenctor.py
Labels: hacktoberfest-accepted

#179 Added questions related to graphs
  Graph/BFS-breadth-first-search.cpp
  Graph/DFS-depth-first-search.cpp
  Graph/UnionFind/number-of-provinces.cpp
  Graph/UnionFind/redundant-connection.cpp
  Graph/bellman-ford-algorithm.cpp
  Graph/cheapest-flight-with-k-stops.cpp
  Graph/course-schedule-1-or-deadlock-detection.cpp
  Graph/detect-cycle-directed-graph.cpp
  Graph/detect-cycle-undirected-graph.cpp
  Graph/dijkstras-algorithm.cpp
  Graph/disjoint-sets-optimized.cpp
  Graph/disjoint-sets.cpp
  Graph/euler-circuit-and-path.cpp
  Graph/flood-fill.cpp
  Graph/floyd-warshall-algorithm.cpp
  Graph/kosaraju-algorithm.cpp
  Graph/kruskals-algorithm.cpp
  Graph/network-delay-time.cpp
  Graph/num-operations-to-connect-network.cpp
  Graph/number-of-islands.cpp
  Graph/prims-algorithm.cpp
  Graph/print-adjacency-list.cpp
  Graph/rat-in-a-maze.cpp
  Graph/topological-sort.cpp
Labels: hacktoberfest-accepted, reviewed

#172 Update index.html
  website.html/index.html
Labels: hacktoberfest-accepted

#186 weather website
  web_server/package-lock.json
  web_server/package.json
  web_server/public/css/style.css
  web_server/public/img/canIHelpYou.png
  web_server/public/img/lost.jpg
  web_server/public/img/my_current_pic.jpg
  web_server/public/img/my_pic.jpg
  web_server/public/img/weather.png
  web_server/public/img/whatHappened.jpeg
  web_server/public/img/whatHappened.jpg
  web_server/public/js/app.js
  web_server/public/js/weather.js
  web_server/src/app.js
  web_server/src/style.css
  web_server/src/utils/forecast.js
  web_server/src/utils/geocode.js
  web_server/templates/partials/footer.hbs
  web_server/templates/partials/header.hbs
  web_server/templates/views/404.hbs
  web_server/templates/views/about.hbs
  web_server/templates/views/help.hbs
  web_server/templates/views/index.hbs
Labels: hacktoberfest-accepted, reviewed

#191 Added "Quick Image Editor", a JS project to edit your pictures online
  quick image editor/README.md
  quick image editor/index.html
  quick image editor/res/android-chrome-192x192.png
  quick image editor/res/android-chrome-512x512.png
  quick image editor/res/apple-touch-icon.png
  quick image editor/res/favicon-16x16.png
  quick image editor/res/favicon-32x32.png
  quick image editor/res/favicon.ico
  quick image editor/res/sample-image.svg
  quick image editor/res/seo.png
  quick image editor/script.js
  quick image editor/style.css
Labels: hacktoberfest-accepted

#196 Drum Kit Website added
  drumKit-Website-main/Website snap.png
  drumKit-Website-main/images/crash.png
  drumKit-Website-main/images/kick.png
  drumKit-Website-main/images/snare.png
  drumKit-Website-main/images/tom1.png
  drumKit-Website-main/images/tom2.png
  drumKit-Website-main/images/tom3.png
  drumKit-Website-main/images/tom4.png
  drumKit-Website-main/index.html
  drumKit-Website-main/index.js
  drumKit-Website-main/sounds/crash.mp3
  drumKit-Website-main/sounds/kick-bass.mp3
  drumKit-Website-main/sounds/snare.mp3
  drumKit-Website-main/sounds/tom-1.mp3
  drumKit-Website-main/sounds/tom-2.mp3
  drumKit-Website-main/sounds/tom-3.mp3
  drumKit-Website-main/sounds/tom-4.mp3
  drumKit-Website-main/styles.css
Labels: hacktoberfest-accepted

#198 Added TEXTMANIA React Application
  TextMania/.gitignore
  TextMania/README.md
  TextMania/package-lock.json
  TextMania/package.json
  TextMania/public/favicon.png
  TextMania/public/index.html
  TextMania/public/logo192.png
  TextMania/public/logo512.png
  TextMania/public/manifest.json
  TextMania/public/robots.txt
  TextMania/src/App.css
  TextMania/src/App.js
  TextMania/src/App.test.js
  TextMania/src/components/About.js
  TextMania/src/components/Alert.js
  TextMania/src/components/Footer.js
  TextMania/src/components/Form.js
  TextMania/src/components/Navbar.js
  TextMania/src/index.css
  TextMania/src/index.js
  TextMania/src/logo.svg
  TextMania/src/reportWebVitals.js
  TextMania/src/setupTests.js
Labels: hacktoberfest-accepted, reviewed

#197 ADD: Joke Generator
  Joke Generator/index.html
Labels: hacktoberfest-accepted, reviewed

#171 Added an end to end recipe application
  End To End Recipe Application/index.html
  End To End Recipe Application/node_modules/node-fetch/CHANGELOG.md
  End To End Recipe Application/node_modules/node-fetch/LICENSE.md
  End To End Recipe Application/node_modules/node-fetch/README.md
  End To End Recipe Application/node_modules/node-fetch/browser.js
  End To End Recipe Application/node_modules/node-fetch/lib/index.es.js
  End To End Recipe Application/node_modules/node-fetch/lib/index.js
  End To End Recipe Application/node_modules/node-fetch/lib/index.mjs
  End To End Recipe Application/node_modules/node-fetch/package.json
  End To End Recipe Application/package-lock.json
  End To End Recipe Application/script.js
  End To End Recipe Application/style.css
Labels: hacktoberfest-accepted, reviewed

#195 Next greater element Question Answer HTML page
  Create a simple Html page/Next_Greater_Element.html
Labels: hacktoberfest-accepted, reviewed

#200 Adding a weather app in HTML CSS JS
  Weather App/index.html
  Weather App/script.js
  Weather App/w.gif
  Weather App/w.jfif
  Weather App/w.png
Labels: hacktoberfest-accepted

#209 Face detector using python
  facedetector using python.ipynb
Labels: hacktoberfest-accepted

#214 added bubble_sort_visualiser in python using pygame.
  bubble_sort_visualiser.py
Labels: hacktoberfest-accepted, reviewed

#215 Update A Memory_Game
  Memory-Game/index.html
  Memory-Game/index.js
  Memory-Game/sounds/blue.mp3
  Memory-Game/sounds/green.mp3
  Memory-Game/sounds/red.mp3
  Memory-Game/sounds/wrong.mp3
  Memory-Game/sounds/yellow.mp3
  Memory-Game/styles.css
Labels: hacktoberfest-accepted

#221 Added a crud application using Html,css,js
  crud/CRUD.css
  crud/CRUD.html
  crud/CRUD.js
Labels: hacktoberfest-accepted, reviewed

#224 Merge this Registration Form built using html and css
  Registration_form_html_css/form.html
  Registration_form_html_css/style.css
  Registration_form_html_css/thanks.html
Labels: hacktoberfest-accepted, reviewed
